### ISSUE TITLE
type and select doesn't work.

### ISSUE THREAD

**Issue by onur-celik** [Taranys/ui-select2-sortable#8]
with regular select2 you can type the keyword and it automatically removes the options other than what you type. this feature doesn't work anymore even if they match and makes the typed list item underlined.

**Comment by Taranys** [comment]
Hi,

Can you give me a code example to reproduce this ?? I use this feature too on my project without any troubles.

I also try on included eample : docs/index.html and it seems ok.

I also need you angular and select2 version :)

**Comment by onur-celik** [comment]
angularjs version "1.3.14" and angular-ui-select2 version "0.0.5" are included into my project. 
your example does not work as well. I mean it matches what you type but does not select it at all.
let me upload an example.

![screen shot 2015-03-04 at 10 32 36](https://cloud.githubusercontent.com/assets/763264/6480212/d0c21e60-c259-11e4-8273-52ec72ff3389.png)

as you see in the screen shot; even though I type the word "two" it does not select the "two". If I press Enter after I type "two" it's gonna select "three". See what I mean?

**Comment by Taranys** [comment]
Thanks I understand :)

In fact, for performance reason, I don't filter my data : I assumed data comes from server and it should be already fitlered.

I just updated my example to fix the behavior you shown 9bfa23657223e8ee029272f1bda2ffbdeb717345

To solve this, you have two solutions : 
  - Use simple-data instead of simple-query (only if you don't use any ajax request and it will simplify your code)
  - Use simple-query with a $filter like https://github.com/Taranys/ui-select2-sortable#filter-data-by-term

Hope I answer to your question. I'm waiting your feedback to close the issue
